In [14]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler


In [15]:
df = pd.read_csv('Water Quality Prediction.csv')
df.head()

Index        pH      Iron   Nitrate    Chloride           Lead      Zinc  \
0      0  8.332988  0.000083  8.605777  122.799772   3.710000e-52  3.434827   
1      1  6.917863  0.000081  3.734167  227.029851   7.850000e-94  1.245317   
2      2  5.443762  0.020106  3.816994  230.995630   5.290000e-76  0.528280   
3      3  7.955339  0.143988  8.224944  178.129940  4.000000e-176  4.027879   
4      4  8.091909  0.002167  9.925788  186.540872  4.170000e-132  3.807511   

            Color  Turbidity  Fluoride  ...  Chlorine     Manganese  \
0       Colorless   0.022683  0.607283  ...  3.708178  2.270000e-15   
1    Faint Yellow   0.019007  0.622874  ...  3.292038  8.020000e-07   
2    Light Yellow   0.319956  0.423423  ...  3.560224  7.007989e-02   
3  Near Colorless   0.166319  0.208454  ...  3.516907  2.468295e-02   
4    Light Yellow   0.004867  0.222912  ...  3.177849  3.296139e-03   

   Total Dissolved Solids  Source  Water Temperature  Air Temperature  \
0              332.118789     NaN                NaN        43.493324   
1              284.641984    Lake          15.348981        71.220586   
2              570.054094   River          11.643467        44.891330   
3              100.043838  Ground          10.092392        60.843233   
4              168.075545  Spring          15.249416        69.336671   

      Month   Day  Time of Day  Potability  
0   January  29.0          4.0           0  
1  November  26.0         16.0           0  
2   January  31.0          8.0           0  
3     April   1.0         21.0           0  
4      June  29.0          7.0           0  

[5 rows x 24 columns]

In [16]:
df.isna().sum()

Index                         0
pH                        20231
Iron                       6991
Nitrate                   18695
Chloride                  30834
Lead                       4684
Zinc                      27675
Color                       981
Turbidity                  8694
Fluoride                  33218
Copper                    34882
Odor                      31332
Sulfate                   34525
Conductivity              28803
Chlorine                  10162
Manganese                 19339
Total Dissolved Solids      298
Source                    15535
Water Temperature         29688
Air Temperature            5303
Month                     16921
Day                       17549
Time of Day               20361
Potability                    0
dtype: int64

In [17]:
df.shape

(1048575, 24)

In [18]:
# remove all rows with Nan values

df.dropna(inplace=True) # modifies the dataframe in place

In [19]:
# check for duplicate rows
duplicate_rows = df[df.duplicated()]
if duplicate_rows.count().sum() == 0:
   print("No duplicate rowa")
else:
   print("Duplicate rows are present")

No duplicate rowa


In [20]:
# split the dataset into x and y
X = df.drop(['Potability', 'Month', 'Day', 'Time of Day', 'Index'], axis=1) # axis=1 indicates we are dropping a column, not a row
Y = df['Potability']
X

pH          Iron   Nitrate    Chloride           Lead  \
1        6.917863  8.050000e-05  3.734167  227.029851   7.850000e-94   
2        5.443762  2.010586e-02  3.816994  230.995630   5.290000e-76   
4        8.091909  2.167128e-03  9.925788  186.540872  4.170000e-132   
7        7.258203  6.110000e-09  9.261676  182.242341  4.400000e-224   
9        7.100650  3.019038e-03  3.620641  157.043934  6.460000e-148   
...           ...           ...       ...         ...            ...   
1048569  6.957090  3.823323e-03  2.256611  142.981428   3.700000e-52   
1048570  8.186428  1.977157e-02  5.968850  115.963429  1.590000e-113   
1048571  8.046225  1.160000e-05  3.678714  148.053168   5.930000e-25   
1048572  7.443582  3.103077e-03  7.893399  174.677900   1.080000e-15   
1048573  6.897232  6.980000e-10  5.757980  125.564223   1.300000e-18   

             Zinc           Color  Turbidity  Fluoride    Copper      Odor  \
1        1.245317    Faint Yellow   0.019007  0.622874  0.437835  1.686049   
2        0.528280    Light Yellow   0.319956  0.423423  0.431588  3.414619   
4        3.807511    Light Yellow   0.004867  0.222912  0.616574  0.795310   
7        0.416478       Colorless   0.047803  1.016196  0.298093  3.144199   
9        0.112994       Colorless   0.050613  0.842107  0.391602  2.713379   
...           ...             ...        ...       ...       ...       ...   
1048569  0.887256    Faint Yellow   0.159260  1.874301  0.261121  0.148123   
1048570  2.277221  Near Colorless   0.020610  1.194165  0.006663  3.149487   
1048571  0.483369  Near Colorless   0.878835  1.203689  0.171610  0.894528   
1048572  1.461659  Near Colorless   0.701053  0.115412  0.641379  3.150154   
1048573  0.804589  Near Colorless   0.156424  0.554729  0.018875  1.997442   

            Sulfate  Conductivity  Chlorine     Manganese  \
1        144.010981    432.844908  3.292038  8.020000e-07   
2        275.702107    990.201209  3.560224  7.007989e-02   
4        175.275175    385.025855  3.177849  3.296139e-03   
7        114.551427    160.062557  2.325094  6.020000e-16   
9        167.417837    583.295321  2.284971  8.840000e-07   
...             ...           ...       ...           ...   
1048569   68.833196    472.795988  3.384594  1.907230e-04   
1048570   43.969084    227.409325  2.718928  2.603963e-02   
1048571   74.133056    124.828663  2.312058  4.427830e-02   
1048572  201.977606    337.630357  3.410297  2.350000e-05   
1048573  204.391754    569.077747  2.803234  3.220000e-19   

         Total Dissolved Solids  Source  Water Temperature  Air Temperature  
1                    284.641984    Lake          15.348981        71.220586  
2                    570.054094   River          11.643467        44.891330  
4                    168.075545  Spring          15.249416        69.336671  
7                    214.553104   River          15.891905        61.139140  
9                    113.909077   River          11.899376        14.010268  
...                         ...     ...                ...              ...  
1048569              155.306913  Spring          17.146633        64.890571  
1048570              220.571485  Stream           5.491908        43.817452  
1048571              406.095969    Lake          10.143768        34.626853  
1048572              439.086461  Spring          14.612881        55.460415  
1048573              278.051032    Well           7.351956        65.055864  

[701056 rows x 19 columns]

In [21]:
cols = X.columns
cols = cols.to_list()

categorical_cols = ['Color', 'Source']

# Create a new list that contains only non-string elements
new_list = [item for item in cols if item not in categorical_cols]
new_list

['pH',
 'Iron',
 'Nitrate',
 'Chloride',
 'Lead',
 'Zinc',
 'Turbidity',
 'Fluoride',
 'Copper',
 'Odor',
 'Sulfate',
 'Conductivity',
 'Chlorine',
 'Manganese',
 'Total Dissolved Solids',
 'Water Temperature',
 'Air Temperature']

In [22]:
# we need x, y values as numpy arrays
X = df.iloc[:, 1:-4].values
Y = df.iloc[:, -1].values

X

array([[6.917862877, 8.05e-05, 3.734166635, ..., 'Lake', 15.34898067,
        71.22058602],
       [5.443761984, 0.020105859, 3.816993832, ..., 'River', 11.64346697,
        44.89132961],
       [8.09190898, 0.002167128, 9.925788275, ..., 'Spring', 15.24941574,
        69.33667064],
       ...,
       [8.046225394, 1.16e-05, 3.678714104, ..., 'Lake', 10.14376847,
        34.62685307],
       [7.443581548, 0.003103077, 7.89339917, ..., 'Spring', 14.61288085,
        55.46041543],
       [6.897231605, 6.98e-10, 5.757980112, ..., 'Well', 7.351956321,
        65.05586392]], dtype=object)

In [23]:
# Label Encode categorical values (1, 2, 3 ... values)
le1 = LabelEncoder()
X[:, 6] = le1.fit_transform(X[:, 6])

le2 = LabelEncoder()
X[:, 16] = le2.fit_transform(X[:, 16])
X[0]


array([6.917862877, 8.05e-05, 3.734166635, 227.0298509, 7.85e-94,
       1.245317068, 1, 0.019007277, 0.622873794, 0.437835305, 1.686049006,
       144.0109807, 432.8449082, 3.29203779, 8.02e-07, 284.6419843, 2,
       15.34898067, 71.22058602], dtype=object)

In [24]:
# Column transform categorical columns (0, 1, 0 ...)
ct1 = ColumnTransformer(transformers=[('encode', OneHotEncoder(), [6])], remainder='passthrough')
X = ct1.fit_transform(X)

ct2 = ColumnTransformer(transformers=[('encode', OneHotEncoder(), [20])], remainder='passthrough')
X = ct2.fit_transform(X)


In [25]:
# Splitting the data set
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=1)
x_train

array([[1.0, 0.0, 0.0, ..., 33.76828319, 13.87340518, 57.21896351],
       [0.0, 0.0, 0.0, ..., 481.2952774, 22.57075076, 66.08116701],
       [0.0, 0.0, 1.0, ..., 520.5272886, 12.5839687, 60.68067714],
       ...,
       [0.0, 0.0, 0.0, ..., 185.6799814, 12.06195018, 96.30836638],
       [0.0, 0.0, 0.0, ..., 30.35605074, 21.49367103, 42.01159904],
       [0.0, 0.0, 1.0, ..., 290.1163126, 15.98191451, 58.19121103]],
      dtype=object)

In [27]:
# Normalize input values

sc = StandardScaler()  # range: -3 to +3
x_train[:, 13:] = sc.fit_transform(x_train[:, 13:])  # 0,1,2 are dummy variables
x_test[:, 13:] = sc.transform(x_test[:, 13:])

x_train[0]

array([0, 0, 1, ..., 1, 1, 0], dtype=int64)